/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBillsRouteImport } from './routes/_app.bills'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLedgerIndexRouteImport } from './routes/_app.ledger.index'
import { Route as AppLedgerPeriodIdRouteImport } from './routes/_app.ledger.$periodId'
import { Route as AppPtoIndexRouteImport } from './routes/_app.pto.index'
import { Route as AppPtoYearRouteImport } from './routes/_app.pto.$year'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerIndexRoute = AppLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerPeriodIdRoute = AppLedgerPeriodIdRouteImport.update({
  id: '/ledger/$periodId',
  path: '/ledger/$periodId',
  getParentRoute: () => AppRoute,
} as any)
const AppPtoIndexRoute = AppPtoIndexRouteImport.update({
  id: '/pto/',
  path: '/pto/',
  getParentRoute: () => AppRoute,
} as any)
const AppPtoYearRoute = AppPtoYearRouteImport.update({
  id: '/pto/$year',
  path: '/pto/$year',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bills': typeof AppBillsRoute
  '/income': typeof AppIncomeRoute
  '/settings': typeof AppSettingsRoute
  '/ledger/$periodId': typeof AppLedgerPeriodIdRoute
  '/pto/$year': typeof AppPtoYearRoute
  '/ledger/': typeof AppLedgerIndexRoute
  '/pto/': typeof AppPtoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bills': typeof AppBillsRoute
  '/income': typeof AppIncomeRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/ledger/$periodId': typeof AppLedgerPeriodIdRoute
  '/pto/$year': typeof AppPtoYearRoute
  '/ledger': typeof AppLedgerIndexRoute
  '/pto': typeof AppPtoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bills': typeof AppBillsRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/ledger/$periodId': typeof AppLedgerPeriodIdRoute
  '/_app/pto/$year': typeof AppPtoYearRoute
  '/_app/ledger/': typeof AppLedgerIndexRoute
  '/_app/pto/': typeof AppPtoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bills'
    | '/income'
    | '/settings'
    | '/ledger/$periodId'
    | '/pto/$year'
    | '/ledger/'
    | '/pto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bills'
    | '/income'
    | '/settings'
    | '/'
    | '/ledger/$periodId'
    | '/pto/$year'
    | '/ledger'
    | '/pto'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bills'
    | '/_app/income'
    | '/_app/settings'
    | '/_app/'
    | '/_app/ledger/$periodId'
    | '/_app/pto/$year'
    | '/_app/ledger/'
    | '/_app/pto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger/': {
      id: '/_app/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AppLedgerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger/$periodId': {
      id: '/_app/ledger/$periodId'
      path: '/ledger/$periodId'
      fullPath: '/ledger/$periodId'
      preLoaderRoute: typeof AppLedgerPeriodIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pto/': {
      id: '/_app/pto/'
      path: '/pto'
      fullPath: '/pto/'
      preLoaderRoute: typeof AppPtoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pto/$year': {
      id: '/_app/pto/$year'
      path: '/pto/$year'
      fullPath: '/pto/$year'
      preLoaderRoute: typeof AppPtoYearRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLedgerPeriodIdRoute: typeof AppLedgerPeriodIdRoute
  AppPtoYearRoute: typeof AppPtoYearRoute
  AppLedgerIndexRoute: typeof AppLedgerIndexRoute
  AppPtoIndexRoute: typeof AppPtoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppLedgerPeriodIdRoute: AppLedgerPeriodIdRoute,
  AppPtoYearRoute: AppPtoYearRoute,
  AppLedgerIndexRoute: AppLedgerIndexRoute,
  AppPtoIndexRoute: AppPtoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
